### ISSUE TITLE
docker container build - cypress download error

### ISSUE THREAD

**Issue by klaute** [victronenergy/venus-docker#10]
Hello,

I'm facing some build errors.

I try to build the docker container on a Orange Pi one (I don't own a Raspberry pi anymore) running Armbian linux.

BOARD_NAME="Orange Pi One"
BOARDFAMILY=sun8i 
VERSION=22.05.1 
LINUXFAMILY=sunxi
ARCH=arm
IMAGE_TYPE=stable

The build is complaining about cypress. It can't download the required content.
The requested link is: https://download.cypress.io/desktop/6.9.1?platform=linux&arch=ia32
But it's only available by using the following URL: https://download.cypress.io/desktop/6.9.1?platform=linux

I tried to fix it but without success.

Please see detail error messages in attached log.

[nocolor_build.log](https://github.com/victronenergy/venus-docker/files/8898981/nocolor_build.log)

**Comment by AlexImb** [comment]
Could you please try building the image again using the latest master? That seems to have fixed for users building on M1 MacBook devices, which are also `arm` based.

Alternatively, you can always pull the latest version from Docker Hub: https://hub.docker.com/r/victronenergy/venus-docker

**Comment by AlexImb** [comment]
Just built a new image on an M1 Mac with the latest submodules and it worked.
