### ISSUE TITLE
creating Venus-docker image on Mac (m1)

### ISSUE THREAD

**Issue by klaute** [victronenergy/venus-docker#11]
Hello,

I'm fixed the build of the Venus-docker image on a Mac m1.

I faced a lot of error messages.

At first I had to run dos2unix for the build.sh script.
Same for the run.sh script.
Now it run's without an error message.

Next I got hundreds of the following messages:

_#43 28.92   Line 90:4:   Delete `␍`  prettier/prettier_

File type of several files is ASCII text. Example:
venus-html5-app/src/serviceWorkerRegistration.ts: ASCII text

I fixed this error by appending the following line into the file _venus-html5-app/.eslintrc.js_:
```
...
'prettier/prettier': [
  'error',
  {
        printWidth: 120,
        semi: false,
        **'endOfLine': 'auto',**
  }
]
```

After that I got a green build.

**Comment by klaute** [comment]
The run.sh script and also the scripts in the container itself are also affected to the file encoding problem mentioned in my previous post.

I can't get the software run on a Mac for now.

**Comment by tpomerhn** [comment]
I had similar issues on Windows 11, as well, with Docker 4.11.1. Was not able to build from either a Windows command prompt or Powershell prompt - had the same error as klaute on Mac. Tried adding the 'endofline' fix, and it also allowed me to build the docker image like klaute did, but upon run, all the files were unable to be run (i.e. run.sh). I could run the docker image manually with all the port forwards, but the scripts inside the container (run_with_simulation.sh or simulation.sh) would not run.

The only way I could get this to build and run properly was by downloading the Ubuntu "app" from the Windows 11 App Store, run a terminal with a root bash shell, and clone/build/execute the run.sh command entirely from inside the Ubuntu shell. So this likely only really works (as it is on this commit) if cloned/built from github natively on a linux shell.

Would be nice if the repo could be tweaked to work natively on Windows and Mac without dos2unix/eslinter fixes, but for now I have this workaround.

**Comment by AlexImb** [comment]
Hi, I just built the image on an M1 MacBook Pro a few hours ago. All worked well! 

Could you please try again?

**Comment by AlexImb** [comment]
Alternatively, you can always pull the latest version from Docker Hub: https://hub.docker.com/r/victronenergy/venus-docker

**Comment by tpomerhn** [comment]
Built fine today using latest download, on M1 MBP, instead of Windows.

My other issue (https://github.com/victronenergy/venus-docker/issues/13) is still present, though. I can start the container fine with a simulation, but the remote console goes to a refused connection port.

![image](https://user-images.githubusercontent.com/110104413/189005474-4a64d4b3-ceb0-417e-bcb6-6298775ae270.png)

However, I would personally consider the issue resolved at this point for M1 Macs using the latest origin/master.

**Comment by AlexImb** [comment]
Great. Happy it's fixed for you as well.
