### ISSUE TITLE
error when building mqtt docker image

### ISSUE THREAD

**Issue by veeriz** [victronenergy/venus-docker#14]
Step 4/47 : RUN npm install
 ---> Running in 40c34736c780

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbe8286a4

please advise on howto proceed :)

**Comment by AlexImb** [comment]
Could you please try building the image again using the latest master? 

Alternatively, you can always pull the latest version from Docker Hub: https://hub.docker.com/r/victronenergy/venus-docker

**Comment by Head** [comment]
Same here, with latest master on a Raspberry Pi 4:

This is related to: https://github.com/nodejs/docker-node/issues/1589
