### ISSUE TITLE
node-sass not found

### ISSUE THREAD

**Issue by boerni** [victronenergy/venus-docker#6]
Hi,

on Raspberry 3 the build failed because node-sass could not be installed.

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.14.1/linux-arm-83_binding.node": 

HTTP error 404 Not Found

I think this error belongs to the included venus-html5-app.

Is there a fix or workaround?

Thanks

**Comment by AlexImb** [comment]
Hi,

node-sass does not support the ARM architecture and there is no official binary for it.

As a workaround, you can try to use one of the prebuilt Docker images from https://hub.docker.com/r/victronenergy/venus-docker You can pull the image, tag it as `mqtt` and then use the `run.sh` as described in the README.

Alternatively, if you still want to build your own image, you can comment out the stage responsible for building the `venus-html5-app`. 

If you still want to include the `venus-html5-app` without building it, a built version of the app can be downloaded from https://github.com/victronenergy/venus-html5-app/releases, extracted into the `venus-html5-app` folder and copied into the `venus-docker` image by changing `COPY --from=html5-app ./dist/ /var/www/venus_app/` into `COPY ./venus-html5-app/dist/ /var/www/venus_app/`

**Comment by boerni** [comment]
Thanks for the answer!
The prebuild Docker image is all I need (I hope ;-) ).

I tried it with the prebuild image like you described it, but I get this error:
standard_init_linux.go:211: exec user process caused "exec format error"

Is this container build for x86_64?

Thanks!

**Comment by AlexImb** [comment]
The image is built for linux/amd64 (Linux x86_64) by a GitLab Action for every push in this repository. There is no ARM version at the moment. You can try to build one by performing the steps described above for getting a prebuilt `venus-html5-app` release into the image.

You might also want to take a look at other projects that can be hosted on Raspberry Pi 3 such as https://github.com/victronenergy/venus-docker-grafana and https://github.com/victronenergy/venus/wiki/raspberrypi-install-venus-image

Depending on you use case, these projects might be more useful.

**Comment by boerni** [comment]
Thanks Alex,

I just compiled the docker image like you explained, with the pre build html5 app.
Docker is starting and I can also open the html5 app on port 8080, but if I want to configure everything, and click on the "Remote Control" button, it opens a iframe pointing to the pi on port 80 where is nothing listening.

How can I configure everything to get my BMV 700 (is there a documentation?) data sending to the VRM Portal and as bonus to see it in the html5 app ;-)

**Comment by mpvader** [comment]
Hi @boerni I think there is a misunderstanding.

This docker is a data simulator. Not something that you can use for a real victron system.

See the intro in the readme, I rewrote that just now to make it more clear.

**Comment by boerni** [comment]
Oh nooooo :-/ Sorry, seems like I didn't read this so exacly.

Anyway, thanks all for your help :-)

**Comment by mpvader** [comment]
Very welcome! I’ll close this issue now. Best cost vs effort option I can offer you to monitor your system is to get a raspberrypi, see link by @AlexImb
